services:
  postgres:
    image: postgres:18.3
    container_name: plannify_postgres
    environment:
      POSTGRES_DB: plannify_db
      POSTGRES_USER: plannify_user
      POSTGRES_PASSWORD: plannify_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - plannify_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U plannify_user -d plannify_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8
    container_name: plannify_redis
    ports:
      - "6379:6379"
    networks:
      - plannify_network
    restart: unless-stopped

  garage:
    image: docker.io/dxflrs/garage:v2.2.0
    container_name: "garage"
    ports:
      - 3900:3900
      - 3901:3901
      - 3902:3903
      - 3903:3903
    volumes:
      - ./garage.toml:/etc/garage.toml
      - garage_data:/var/lib/garage
    networks:
      - plannify_network
    restart: unless-stopped
    tty: true
    healthcheck:
      test: ["CMD", "/garage", "-c", "/etc/garage.toml", "status"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  garage-init:
    image: docker:cli
    container_name: garage_init
    depends_on:
      garage:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts/garage-init.sh:/garage-init.sh:ro
      - .:/workspace
    command: sh /garage-init.sh
    restart: on-failure

  garage-ui:
    image: khairul169/garage-webui:latest
    container_name: garage-webui
    restart: unless-stopped
    ports:
      - 3909:3909
    volumes:
      - ./garage.toml:/etc/garage.toml:ro
    environment:
      API_BASE_URL: "http://garage:3903"
      S3_ENDPOINT_URL: "http://garage:3900"
      API_ADMIN_KEY: "QEP5Uwqit/qVoRqBV2pVoK86iW98koYuu1WumqzBFmA="
    networks:
      - plannify_network

  pdf-service:
    image: ghcr.io/plannify-truck-driver/pdf-service:latest
    container_name: plannify_pdf_service
    ports:
      - "4000:4000"
    environment:
      HOST: "0.0.0.0"
      PORT: 4000
    networks:
      - plannify_network
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # UI web
      - "4317:4317" # OTLP gRPC
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - plannify_network

volumes:
  postgres_data:
    driver: local
  garage_data:
    driver: local

networks:
  plannify_network:
    driver: bridge
